/**
语言包定义

    'pl_monaco_loading_error_7r' => 'Monaco编辑器加载错误',
    'pl_web_worker_fallback_7r' => 'Web Worker创建失败，回退到主线程',
    'pl_editor_creation_error_7r' => '编辑器创建错误',
    'pl_welcome_message_7r' => '欢迎使用侧边栏记事本！',
    'pl_start_typing_7r' => '您可以在这里开始输入笔记。',
    'pl_test_monaco_7r' => '测试Monaco编辑器配置',
    'pl_test_success_7r' => '测试成功',
    'pl_test_failed_7r' => '测试失败',
    'pl_simple_monaco_7r' => '简化Monaco加载器',
    'pl_monaco_ready_7r' => 'Monaco编辑器准备就绪',
    'pl_test_manifest_7r' => '测试Manifest配置',
    'pl_manifest_valid_7r' => 'Manifest配置有效',
    'pl_manifest_invalid_7r' => 'Manifest配置无效',
    'pl_basic_test_7r' => '基础功能测试',
    'pl_monaco_loaded_7r' => 'Monaco编辑器已加载',
    'pl_monaco_not_loaded_7r' => 'Monaco编辑器未加载',
    'pl_monaco_config_7r' => 'Monaco配置',
    'pl_worker_disabled_7r' => 'Web Worker已禁用',
    'pl_storage_save_7r' => '保存内容',
    'pl_storage_load_7r' => '加载内容',
    'pl_storage_error_7r' => '存储错误',
    'pl_auto_save_7r' => '自动保存',
    'pl_content_loaded_7r' => '内容已加载',
    'pl_state_restored_7r' => '状态已恢复',
    'pl_toolbar_save_7r' => '保存',
    'pl_toolbar_export_7r' => '导出',
    'pl_toolbar_saved_7r' => '已保存',
    'pl_toolbar_exported_7r' => '已导出',
    'pl_export_success_7r' => '导出成功',
    'pl_export_error_7r' => '导出失败',
    'pl_statusbar_last_save_7r' => '上次保存',
    'pl_statusbar_never_saved_7r' => '从未保存',
    'pl_statusbar_manual_save_7r' => '手动保存',
    'pl_statusbar_settings_7r' => '设置',
    'pl_settings_theme_7r' => '主题风格',
    'pl_settings_theme_light_7r' => '明亮',
    'pl_settings_theme_dark_7r' => '暗黑',
    'pl_settings_auto_save_interval_7r' => '自动保存时间',
    'pl_settings_exchange_url_7r' => '文本中转站网址',
    'pl_settings_save_7r' => '保存',
    'pl_settings_cancel_7r' => '取消',
    'pl_manual_save_success_7r' => '手动保存成功',
    'pl_settings_saved_7r' => '设置已保存',
    'pl_file_save_success_7r' => '文件保存成功',
    'pl_file_save_error_7r' => '文件保存失败',
    'pl_file_read_success_7r' => '文件读取成功',
    'pl_file_read_error_7r' => '文件读取失败',
    'pl_file_not_found_7r' => '文件不存在',
    'pl_tab_noter_7r' => '浏览器记事',
    'pl_tab_exchange_7r' => '文本中转站',
**/

// 语言包对象
window.langJS_7ree = {
    pl_monaco_loading_error_7r: 'Monaco编辑器加载错误',
    pl_web_worker_fallback_7r: 'Web Worker创建失败，回退到主线程',
    pl_editor_creation_error_7r: '编辑器创建错误',
    pl_welcome_message_7r: '欢迎使用侧边栏记事本！',
    pl_start_typing_7r: '您可以在这里开始输入笔记。',
    pl_test_monaco_7r: '测试Monaco编辑器配置',
    pl_test_success_7r: '测试成功',
    pl_test_failed_7r: '测试失败',
    pl_simple_monaco_7r: '简化Monaco加载器',
    pl_monaco_ready_7r: 'Monaco编辑器准备就绪',
    pl_test_manifest_7r: '测试Manifest配置',
    pl_manifest_valid_7r: 'Manifest配置有效',
    pl_manifest_invalid_7r: 'Manifest配置无效',
    pl_basic_test_7r: '基础功能测试',
    pl_monaco_loaded_7r: 'Monaco编辑器已加载',
    pl_monaco_not_loaded_7r: 'Monaco编辑器未加载',
    pl_monaco_config_7r: 'Monaco配置',
    pl_worker_disabled_7r: 'Web Worker已禁用',
    pl_storage_save_7r: '保存内容',
    pl_storage_load_7r: '加载内容',
    pl_storage_error_7r: '存储错误',
    pl_auto_save_7r: '自动保存',
    pl_content_loaded_7r: '内容已加载',
    pl_state_restored_7r: '状态已恢复',
    pl_toolbar_save_7r: '保存',
    pl_toolbar_export_7r: '导出',
    pl_toolbar_saved_7r: '已保存',
    pl_toolbar_exported_7r: '已导出',
    pl_export_success_7r: '导出成功',
    pl_export_error_7r: '导出失败',
    pl_statusbar_last_save_7r: '上次保存',
    pl_statusbar_never_saved_7r: '从未保存',
    pl_statusbar_manual_save_7r: '手动保存',
    pl_statusbar_settings_7r: '设置',
    pl_settings_theme_7r: '主题风格',
    pl_settings_theme_light_7r: '明亮',
    pl_settings_theme_dark_7r: '暗黑',
    pl_settings_auto_save_interval_7r: '自动保存时间',
    pl_settings_exchange_url_7r: '文本中转站网址',
    pl_settings_save_7r: '保存',
    pl_settings_cancel_7r: '取消',
    pl_manual_save_success_7r: '手动保存成功',
    pl_settings_saved_7r: '设置已保存',
    pl_file_save_success_7r: '文件保存成功',
    pl_file_save_error_7r: '文件保存失败',
    pl_file_read_success_7r: '文件读取成功',
    pl_file_read_error_7r: '文件读取失败',
    pl_file_not_found_7r: '文件不存在',
    pl_tab_noter_7r: '浏览器记事',
    pl_tab_exchange_7r: '文本中转站'
}; 